FROM ruby:2.5

ENV LANG C.UTF-8
ENV APP_ROOT /app

RUN curl -sSL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get update -qq && apt-get install -y nodejs postgresql-client vim

# For tini
ENV TINI_VERSION v0.18.0
ENV TINI_GPG_KEY 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7
RUN cd /tmp && \
  curl -sSL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc -o tini.asc && \
  curl -sSL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -o /usr/local/bin/tini && \
  gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys ${TINI_GPG_KEY} && \
  gpg --verify tini.asc /usr/local/bin/tini && \
  chmod +x /usr/local/bin/tini && \
  rm tini.asc

RUN mkdir -p ${APP_ROOT}
WORKDIR ${APP_ROOT}

COPY Gemfile* ${APP_ROOT}/
RUN bundle install -j "$(getconf _NPROCESSORS_ONLN)" --retry 5

# Add a script to be executed every time the container starts.
COPY rootfs /
ENTRYPOINT [ "/entrypoint-dev.sh" ]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
