default: &default
  adapter: postgresql
  encoding: utf-8
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
